sudo: required
services::
    - docker

before_install:
    - docker build -t ashiitaka/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true USERNAME/react-test npm test

after_sucecess:
    - docker build -t ashiitaka/multi-client ./client
    - docker build -t ashiitaka/multi-nginx ./nginx
    - docker build -t ashiitaka/multi-server ./server
    - docker build -t ashiitaka/multi-worker ./worker
    # login
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #push to dockerr
    - docker push ashiitaka/multi-client
    - docker push ashiitaka/multi-nginx
    - docker push ashiitaka/multi-server
    - docker push ashiitaka/multi-worker
    